import React from "react";
import "./privacy.css";
import Footer from "../components/Footer";

export default function privacy() {
  return (
    <div className=" privacy mx-auto w-11/12 md:max-w-7xl">
      <h1>Privacy Policy for Human Value Extractor</h1>
      <p>Effective date: 01 May, 2023</p>
      <p>
        HumanValueExtractor (&#39;us&#39;, &#39;we&#39;, or &#39;our&#39;)
        operates the https://value-detector.schroter.eu website (hereinafter
        referred to as the &#39;Service&#39;). This page informs you of our
        policies regarding the collection, use, and disclosure of personal data
        when you use our Service and the choices you have associated with that
        data. We use your data to provide and improve the Service. By using the
        Service, you agree to the collection and use of information in
        accordance with this policy.
      </p>
      <p>
        If you have additional questions or require more information about our
        Privacy Policy, do not hesitate to contact us.
      </p>
      <p>
        This Privacy Policy applies only to our online activities and is valid
        for visitors to our website with regards to the information that they
        shared and/or collect in Ai One Pager. This policy is not applicable to
        any information collected offline or via channels other than this
        website.
      </p>
      <p>
        By using our website, you hereby consent to our Privacy Policy and agree
        to its terms.
      </p>
      <h2>Definitions</h2>
      <h4>Service</h4>
      <p>
        Service is the https://value-detector.schroter.eu website operated by
        Human Value Detector (Daniel Schroter)
      </p>
      <h4>Personal Data</h4>
      <p>
        Personal Data means data about a living individual who can be identified
        from those data (or from those and other information either in our
        possession or likely to come into our possession).
      </p>
      <h4>Usage Data</h4>
      <p>
        Usage Data is data collected automatically either generated by the use
        of the Service or from the Service infrastructure itself (for example,
        the duration of a page visit).
      </p>
      <h4>Cookies</h4>
      <p>
        Cookies are small files stored on your device (computer or mobile
        device).
      </p>
      <h2>Information we collect and use</h2>
      <p>
        The personal data that you are asked to provide, and the reasons why you
        are asked to provide it, will be made clear to you at the point we ask
        you to provide your personal information.
      </p>
      <p>
        If you contact us directly, we may receive additional information about
        you such as your name, email address, phone number, the contents of the
        message and/or attachments you may send us, and any other information
        you may choose to provide.
      </p>
      <h2>How we use your information</h2>
      <p>We use the information we collect in various ways, including to:</p>
      <ul>
        <li>Provide, operate, and maintain our website</li>
        <li>To provide support</li>
        <li>Find and prevent fraud</li>
        <li>To monitor the usage of the service</li>
        <li>To detect, prevent and address technical issues</li>
      </ul>
      <h2>Log Files</h2>
      <p>
        Human Value Detector follows a standard procedure of using log files.
        These files log visitors when they visit websites. All hosting companies
        do this and a part of hosting services&#39; analytics. The information
        collected by log files include internet protocol (IP) addresses, browser
        type, Internet Service Provider (ISP), date and time stamp,
        referring/exit pages, and possibly the number of clicks. These are not
        linked to any information that is personally identifiable. The purpose
        of the information is for analyzing trends, administering the site,
        tracking users&#39; movement on the website, and gathering demographic
        information. We use Vercel Inc. as hosting provider.
      </p>
      <h2>Transfer of Data</h2>
      <p>
        Human Value Detectors&#39;s Privacy Policy does not apply to other
        advertisers or websites. Thus, we are advising you to consult the
        respective Privacy Policies of these third-party ad servers for more
        detailed information. It may include their practices and instructions
        about how to opt-out of certain options.{" "}
      </p>
      <h2>Disclosure Of Data</h2>
      <h4>Legal Requirements</h4>
      <p>
        Human Value Detector may disclose your Personal Data in the good faith
        belief that such action is necessary to:
      </p>
      <ul>
        <li>To comply with a legal obligation</li>
        <li>
          To protect and defend the rights or property of HumanValueDetector
        </li>
        <li>
          To prevent or investigate possible wrongdoing in connection with the
          Service
        </li>
        <li>
          To protect the personal safety of users of the Service or the public
        </li>
        <li> To protect against legal liability</li>
      </ul>
      <h2>Security of Data</h2>
      <p>
        The security of your data is important to us, but remember that no
        method of transmission over the Internet, or method of electronic
        storage is 100% secure. While we strive to use commercially acceptable
        means to protect your Personal Data, we cannot guarantee its absolute
        security.
      </p>
      <h2>
        Legal Basis for Processing Personal Data under the General Data
        Protection Regulation (GDPR)
      </h2>
      <p>
        If you are from the European Economic Area (EEA), HumanValueDetector
        legal basis for collecting and using the personal information described
        in this Privacy Policy depends on the Personal Data we collect and the
        specific context in which we collect it. HumanValueDetector may process
        your Personal Data because:
      </p>
      <ul>
        <li>We need to perform a contract with you</li>
        <li>You have given us permission to do so</li>
        <li>
          The processing is in our legitimate interests and it is not overridden
          by your rights
        </li>
        <li>For payment processing purposes</li>
        <li>To comply with the law</li>
      </ul>
      <h2>Retention of Data</h2>
      <p>
        Human Value Detector will retain your Personal Data only for as long as
        is necessary for the purposes set out in this Privacy Policy. We will
        retain and use your Personal Data to the extent necessary to comply with
        our legal obligations (for example, if we are required to retain your
        data to comply with applicable laws), resolve disputes and enforce our
        legal agreements and policies. <br /> Human Value Detector will also
        retain Usage Data for internal analysis purposes. Usage Data is
        generally retained for a shorter period of time, except when this data
        is used to strengthen the security or to improve the functionality of
        our Service, or we are legally obligated to retain this data for longer
        periods.
      </p>
      <h2>Service Providers</h2>
      We may employ third party companies and individuals to facilitate our
      Service (&#39;Service Providers&#39;), to provide the Service on our
      behalf, to perform Service-related services or to assist us in analyzing
      how our Service is used. These third parties have access to your Personal
      Data only to perform these tasks on our behalf and are obligated not to
      disclose or use it for any other purpose.
      <h2>CCPA Privacy Rights (Do Not Sell My Personal Information)</h2>
      <p>
        Under the CCPA, among other rights, California consumers have the right
        to:
      </p>
      <p>
        Request that a business that collects a consumer&#39;s personal data
        disclose the categories and specific pieces of personal data that a
        business has collected about consumers.
      </p>
      <p>
        Request that a business delete any personal data about the consumer that
        a business has collected.
      </p>
      <p>
        Request that a business that sells a consumer&#39;s personal data, not
        sell the consumer&#39;s personal data.
      </p>
      <p>
        If you make a request, we have one month to respond to you. If you would
        like to exercise any of these rights, please contact us.
      </p>
      <h4>
        Our Policy on &#39;Do Not Track&#39; Signals under the California Online
        Protection Act (CalOPPA)
      </h4>
      <p>
        We do not support Do Not Track (&#39;DNT&#39;). Do Not Track is a
        preference you can set in your web browser to inform websites that you
        do not want to be tracked. You can enable or disable Do Not Track by
        visiting the Preferences or Settings page of your web browser.
      </p>
      <h2>GDPR Data Protection Rights</h2>
      <p>
        We would like to make sure you are fully aware of all of your data
        protection rights. Every user is entitled to the following:
      </p>
      <p>
        The right to access – You have the right to request copies of your
        personal data. We may charge you a small fee for this service.
      </p>
      <p>
        The right to rectification – You have the right to request that we
        correct any information you believe is inaccurate. You also have the
        right to request that we complete the information you believe is
        incomplete.
      </p>
      <p>
        The right to erasure – You have the right to request that we erase your
        personal data, under certain conditions.
      </p>
      <p>
        The right to restrict processing – You have the right to request that we
        restrict the processing of your personal data, under certain conditions.
      </p>
      <p>
        The right to object to processing – You have the right to object to our
        processing of your personal data, under certain conditions.
      </p>
      <p>
        The right to data portability – You have the right to request that we
        transfer the data that we have collected to another organization, or
        directly to you, under certain conditions.
      </p>
      <p>
        If you make a request, we have one month to respond to you. If you would
        like to exercise any of these rights, please contact us.
      </p>
      <h2>Links to Other Sites</h2>
      <p>
        Our Service may contain links to other sites that are not operated by
        us. If you click on a third party link, you will be directed to that
        third party&#39;s site. We strongly advise you to review the Privacy
        Policy of every site you visit. We have no control over and assume no
        responsibility for the content, privacy policies or practices of any
        third party sites or services.
      </p>
      <h2>Children&#39;s Information</h2>
      <p>
        Another part of our priority is adding protection for children while
        using the internet. We encourage parents and guardians to observe,
        participate in, and/or monitor and guide their online activity.
      </p>
      <p>
        Ai One Pager does not knowingly collect any Personal Identifiable
        Information from children under the age of 18. If you think that your
        child provided this kind of information on our website, we strongly
        encourage you to contact us immediately and we will do our best efforts
        to promptly remove such information from our records.
      </p>
      <h2>Newsletter</h2>
      <p>
        If you subscribe to our newsletter, then we store your email address and
        use this to send the newsletter. Your email address is not made public
        or disclosed to third parties.
        <ul>
          <li>Collected data: Email address</li>
          <li>Purpose of use: Sending of the newsletter requested</li>
          <li>
            Storage period: As a general rule, the data is only stored for as
            long as is needed to fulfill the purpose. For the newsletter, the
            data are stored as long as it is expected that a newsletter will be
            sent and as long as you have not objected to the use of your data.
          </li>
          <li>Legal basis: article 6 (1) a) GDPR – consent</li>
          <li>
            Revocation: You can unsubscribe from our newsletter at any time
            using a link included in each issue. We will then delete your email
            address from our distribution list. As an alternative, you can also
            unsubscribe from our newsletter at any time by sending an email to
            projects@schroter.eu.
          </li>
        </ul>{" "}
        <p>
          {" "}
          We may use ConvertKit as our marketing platform. By clicking below to
          subscribe, you acknowledge that your information will be transferred
          to ConvertKit for processing. Learn more about ConvertKit&#39;s
          privacy practices{" "}
          <a href="https://convertkit.com/privacy" target="_blank">
            here
          </a>
          .
        </p>
      </p>
      <h2>Changes to This Privacy Policy</h2>
      <p>
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page. We will
        let you know via email and/or a prominent notice on our Service, prior
        to the change becoming effective and update the &#39;effective date&#39;
        at the top of this Privacy Policy. You are advised to review this
        Privacy Policy periodically for any changes. Changes to this Privacy
        Policy are effective when they are posted on this page
      </p>
      <h2>Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, please contact us:{" "}
        <br />
        By email: projects@schroter.eu
      </p>
      <Footer></Footer>
    </div>
  );
}
